@extends('admin.layout')
@section('title','Agents')
@section('content')
<div class="page-heading"><div><p class="eyebrow">UNE ÉQUIPE, LES BONS ACCÈS</p><h1>Agents de contrôle<span class="title-dot">.</span></h1><p class="muted">Attribuez uniquement les événements dont chaque agent a besoin.</p></div><a class="button primary" href="#new-agent">@include('admin.icon',['icon'=>'plus']) Nouvel agent</a></div>
<section class="panel"><div class="section-heading"><h2>Votre équipe</h2><span class="badge">{{ count($agents) }} agent(s)</span></div>
@forelse($agents as $agent)
<details class="agent-row" @if((string)old('id')===(string)$agent['id']) open @endif><summary><span class="avatar">{{ mb_substr($agent['fullName'],0,1) }}</span><span><strong>{{ $agent['fullName'] }}</strong><small>{{ $agent['email'] }} · {{ count($agent['eventIds']) }} événement(s)</small></span><span class="badge {{ $agent['isActive'] ? 'green' : 'orange' }}">{{ $agent['isActive'] ? 'Actif' : 'Désactivé' }}</span><span class="text-link">Modifier</span></summary>
<form method="post" action="{{ route('web.agents.update') }}" class="form-stack agent-form">@csrf @method('PATCH')<input type="hidden" name="id" value="{{ $agent['id'] }}"><label>Nom complet<input name="fullName" required maxlength="120" value="{{ (string)old('id')===(string)$agent['id'] ? old('fullName',$agent['fullName']) : $agent['fullName'] }}"></label><label class="check-label"><input type="checkbox" name="isActive" value="1" @checked($agent['isActive'])> Compte actif</label><fieldset><legend>Événements autorisés</legend><div class="assignment-grid">@foreach($events as $item)<label class="assignment"><input type="checkbox" name="eventIds[]" value="{{ $item['id'] }}" @checked(in_array($item['id'],$agent['eventIds']))>{{ $item['name'] }}</label>@endforeach</div>@if(!$events)<p class="muted">Créez d’abord un événement.</p>@endif</fieldset><p class="small muted">Enregistrer révoque les sessions existantes. L’agent devra se reconnecter.</p><button class="button primary">Enregistrer les accès</button></form></details>
@empty<div class="empty"><h3>Votre équipe se construit ici.</h3><p class="muted">Aucun agent créé pour le moment.</p></div>@endforelse
</section>
<section class="panel form-panel" id="new-agent"><div class="section-heading"><div><p class="eyebrow">PRÉPARER UN ACCÈS</p><h2>Nouvel agent</h2></div>@include('admin.icon',['icon'=>'users'])</div><form action="{{ route('web.agents.create') }}" method="post" class="form-stack">@csrf<div class="form-grid"><label>Nom complet<input name="fullName" required maxlength="120" value="{{ old('id') ? '' : old('fullName') }}"></label><label>Email<input name="email" type="email" required maxlength="190" autocomplete="off" value="{{ old('email') }}"></label><label>Mot de passe initial<input name="password" type="password" required minlength="12" maxlength="72" autocomplete="new-password"><small>12 caractères minimum, 72 octets maximum.</small></label></div><label class="check-label"><input type="checkbox" name="isActive" value="1" checked> Compte actif</label><fieldset><legend>Événements autorisés</legend><div class="assignment-grid">@foreach($events as $item)<label class="assignment"><input type="checkbox" name="eventIds[]" value="{{ $item['id'] }}" @checked(!old('id') && in_array($item['id'],old('eventIds',[])))>{{ $item['name'] }}</label>@endforeach</div></fieldset><p class="small muted">Le compte aura le rôle Agent de contrôle. Sans affectation, aucun événement ne sera accessible. Il ne pourra pas confirmer les paiements.</p><button class="button primary">Créer le compte agent</button></form></section>
@endsection
