@extends('admin.layout')
@section('title', 'Vue d’ensemble')
@section('content')
@php($manage = in_array($webUser->role, ['SUPER_ADMIN', 'MANAGER']))
<div class="page-heading"><div><p class="eyebrow">VOTRE CENTRE DE CONTRÔLE</p><h1>Vue d’ensemble<span class="title-dot">.</span></h1><p class="muted">Une vision claire de vos invitations et de vos entrées.</p></div>@if($manage)<a class="button primary" href="{{ route('web.events.new') }}">@include('admin.icon',['icon'=>'plus']) Nouvel événement</a>@endif</div>
@if(!$event)
<section class="panel empty"><span class="icon-tile">@include('admin.icon',['icon'=>'calendar'])</span><h2>Aucun événement accessible</h2><p class="muted">{{ $manage ? 'Créez votre premier événement pour commencer.' : 'Votre organisateur doit vous attribuer un événement.' }}</p></section>
@else
<section class="event-banner"><div class="event-summary"><span class="icon-tile">@include('admin.icon',['icon'=>'calendar'])</span><div><p class="eyebrow">ÉVÉNEMENT SÉLECTIONNÉ</p><h2>{{ $event->name }}</h2><p class="muted">{{ $event->starts_at?->copy()->setTimezone($event->timezone)->format('d/m/Y H:i') ?? 'Date à définir' }} · {{ $event->timezone }} <span class="badge cyan">{{ ['DRAFT'=>'Brouillon','LIVE'=>'En cours','ENDED'=>'Terminé','CANCELLED'=>'Annulé'][$event->status] }}</span></p></div></div><form method="get" class="event-switch"><label for="event-switch">Changer d’événement</label><select name="event" id="event-switch">@foreach($events as $item)<option value="{{ $item->id }}" @selected($item->id === $event->id)>{{ $item->name }}</option>@endforeach</select><button class="button">Afficher</button></form></section>
<section class="metrics" aria-label="Statistiques de l’événement">
@foreach([['total','Tickets émis','ticket','cyan'],['paid','Tickets payés','check','green'],['unpaid','En attente de paiement','clock','orange'],['scanned','Entrées validées','qr','violet']] as [$key,$label,$icon,$tone])
<article class="metric"><div><span class="muted">{{ $label }}</span><span class="icon-tile {{ $tone }}">@include('admin.icon', ['icon'=>$icon])</span></div><strong>{{ number_format($stats[$key],0,',',' ') }}</strong><small>{{ $key === 'scanned' ? 'Scans uniques acceptés' : ($key === 'paid' ? 'Règlements confirmés' : ($key === 'unpaid' ? 'Entrée non autorisée' : 'Invitations de cet événement')) }}</small></article>
@endforeach
</section>
<section class="panel" id="tickets">
    <div class="section-heading"><div><h2>Tickets & paiements</h2><p class="muted">Vérifiez les règlements, puis laissez votre équipe gérer les entrées.</p></div><span class="badge">{{ $tickets->total() }} résultat(s)</span></div>
    <form method="get" class="filters"><input type="hidden" name="event" value="{{ $event->id }}"><label class="search">Rechercher<input name="q" value="{{ request('q') }}" placeholder="Numéro de carte ou invité" maxlength="100"></label><label>Paiement<select name="payment"><option value="">Tous les paiements</option><option value="PAID" @selected(request('payment')==='PAID')>Payé</option><option value="UNPAID" @selected(request('payment')==='UNPAID')>Non payé</option></select></label><label>Contrôle<select name="status"><option value="">Tous les statuts</option>@foreach(['NOT_SCANNED'=>'Non scanné','SCANNED'=>'Scanné','BLOCKED'=>'Bloqué','CANCELLED'=>'Annulé'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></label><button class="button">Filtrer</button><a class="reset" href="{{ route('dashboard',['event'=>$event->id]) }}">Réinitialiser</a></form>
    <form action="{{ route('web.pay', $event->id) }}" method="post" data-payment-form>@csrf
        @if($manage)<div class="bulk"><span><strong data-selection-count>0</strong> ticket(s) sélectionné(s)</span><label class="check-label"><input type="checkbox" name="confirm" value="1" required> Je confirme avoir reçu le règlement.</label><button class="button primary" data-pay-button disabled>Marquer payé</button></div>@endif
        <div class="table-scroll"><table><thead><tr>@if($manage)<th><input type="checkbox" data-select-all aria-label="Sélectionner les tickets non payés de cette page"></th>@endif<th>Ticket</th><th>Invité</th><th>Paiement</th><th>Contrôle</th><th>Payé le</th></tr></thead><tbody>
        @forelse($tickets as $ticket)<tr>@if($manage)<td>@if($ticket->payment_status !== 'PAID')<input type="checkbox" name="ticketIds[]" value="{{ $ticket->id }}" aria-label="Sélectionner {{ $ticket->code }}" data-ticket>@else<span class="muted">—</span>@endif</td>@endif<td><strong class="ticket-code">{{ $ticket->code }}</strong><small>Carte n° {{ $ticket->ticket_number }}</small></td><td>{{ $ticket->guest_name ?: 'Non renseigné' }}</td><td><span class="badge {{ $ticket->payment_status === 'PAID' ? 'green' : 'orange' }}">{{ $ticket->payment_status === 'PAID' ? 'Payé' : 'Non payé' }}</span></td><td><span class="badge {{ $ticket->status === 'SCANNED' ? 'cyan' : '' }}">{{ ['NOT_SCANNED'=>'Non scanné','SCANNED'=>'Scanné','BLOCKED'=>'Bloqué','CANCELLED'=>'Annulé'][$ticket->status] }}</span></td><td>{{ $ticket->paid_at?->format('d/m/Y H:i') ?? '—' }}</td></tr>
        @empty<tr><td colspan="6" class="empty">Aucun ticket ne correspond aux filtres.</td></tr>@endforelse
        </tbody></table></div>
    </form>
    <div class="pagination"><span>{{ $tickets->firstItem() ?? 0 }}–{{ $tickets->lastItem() ?? 0 }} sur {{ $tickets->total() }} tickets</span><div>@if($tickets->previousPageUrl())<a class="button" href="{{ $tickets->previousPageUrl() }}">Précédent</a>@endif<span>Page {{ $tickets->currentPage() }} / {{ $tickets->lastPage() }}</span>@if($tickets->nextPageUrl())<a class="button" href="{{ $tickets->nextPageUrl() }}">Suivant</a>@endif</div></div>
</section>
<div class="two-columns">
@if($manage)<section class="panel"><div class="section-heading"><div><p class="eyebrow">VOS INVITATIONS</p><h2>Importer des tickets</h2></div>@include('admin.icon',['icon'=>'ticket'])</div><p class="muted">CSV séparé par point-virgule ou virgule. Colonnes <code>code</code> et <code>#code</code> pour vos cartes CJA. Les nouveaux tickets sont non payés.</p><form action="{{ route('web.import',$event->id) }}" method="post" enctype="multipart/form-data" class="form-stack">@csrf<label>Fichier CSV (10 Mo maximum)<input type="file" name="file" accept=".csv,.txt" required></label><button class="button">Importer les invitations</button></form></section>@endif
<section class="panel"><div class="section-heading"><div><p class="eyebrow">SUR LE TERRAIN</p><h2>Derniers contrôles</h2></div><span class="badge">10 derniers</span></div><div class="activity">@forelse($logs as $log)<div><span class="icon-tile {{ $log->result==='VALID' ? 'green' : 'orange' }}">@include('admin.icon',['icon'=>$log->result==='VALID' ? 'check' : 'shield'])</span><span><strong>{{ $log->invitation?->code ?? 'Ticket inconnu' }}</strong><small>{{ $log->user?->name ?? 'Agent' }} · {{ $log->created_at->format('d/m H:i') }}</small></span><span class="badge">{{ ['VALID'=>'Validé','UNPAID'=>'Non payé','ALREADY_SCANNED'=>'Déjà scanné','INVALID'=>'Inconnu','BLOCKED'=>'Bloqué','CANCELLED'=>'Annulé','ERROR'=>'Erreur'][$log->result] ?? $log->result }}</span></div>@empty<p class="muted">Aucun contrôle enregistré pour cet événement.</p>@endforelse</div></section>
</div>
@endif
<section id="events"><div class="section-heading"><div><p class="eyebrow">VOTRE PROGRAMME</p><h2>Mes événements <span class="badge">{{ $events->count() }}</span></h2></div></div><div class="event-grid">@foreach($events as $item)<article class="panel event-card"><span class="icon-tile">@include('admin.icon',['icon'=>'calendar'])</span><h3>{{ $item->name }}</h3><p class="muted">{{ $item->starts_at?->copy()->setTimezone($item->timezone)->format('d/m/Y H:i') ?? 'Date à définir' }} · {{ $item->invitations_count }} tickets</p><div class="actions"><a class="button" href="{{ route('dashboard',['event'=>$item->id]) }}">Ouvrir</a>@if($manage)<a class="text-link" href="{{ route('web.events.edit',$item->id) }}">Modifier</a>@endif</div></article>@endforeach</div></section>
@endsection
